### ISSUE TITLE
find function is throwing error

### ISSUE THREAD

**Issue by azamsharp** [vapor/fluent-sqlite#15]
<img width="777" alt="screen shot 2018-05-24 at 1 33 37 pm" src="https://user-images.githubusercontent.com/16604/40505074-c66b2d90-5f58-11e8-81dc-108cf70838bb.png">

I get the following error: 
error: Cannot convert value of type '() throws -> EventLoopFuture<Dish?>' to expected argument type '(Request) throws -> '

**Comment by grundoon** [comment]
(resolved in Discord)

**Comment by Enari** [comment]
What was the solution?

**Comment by calebkleveter** [comment]
@Enari You can't return an optional from a request handler. You have to unwrap it first:

```swift
return Dish.find(id, on: req).unwrap(or: Abort(.notFound))
```

**Comment by Enari** [comment]
@calebkleveter Thank you! Vague error message, I wonder if it could be improved.
