### ISSUE TITLE
Make FluentSQLite usable on iOS

### ISSUE THREAD

**Issue by twof** [vapor/fluent-sqlite#7]
The two most popular options for persistence on iOS (Realm and Core Data), both rely heavily on Objective-C, however, SQLite is available. I think there is a good opportunity to not only have a Swift based persistence layer on iOS, but also promote code sharing between Vapor servers and iOS clients.

Concept:
```swift
// Shared models package, imported by both client and server
class User: Codable {
  let id: Int?
  let name: String
  let age: Int
}

// Client
extension User: SQLiteModel, Migration {}

// Server
extension User: PostgresModel, Migration {}
```

I haven't heavily investigated what is keeping users from utilizing FluentSQLite in their iOS apps, but the first thing that comes to mind is the Console package's use of `Process()`

**Comment by kdawgwilk** [comment]
Would also need to support CocoaPods and Carthage unless we want to hold this off until WWDC and make a bet that SPM will finally be integrated into Xcode

**Comment by twof** [comment]
Technically it's possible to use SPM with iOS apps if we wanted to for testing, but it's really hacky and I'd definitely advise against it in production

https://www.ralfebert.de/ios-examples/xcode/ios-dependency-management-with-swift-package-manager/

Got a macOS Cocoa app running with FluentSQLite using that method

**Comment by twof** [comment]
Good news! `Process` was the only thing preventing this package from being compiled for iOS. It's used in one method in Console and extended in Core, and neither that method nor that extension are used in this package. After wrapping those two in `#if os(OSX)`, the package compiles just fine. Trying  to figure out how to import it into an iOS project now.

**Comment by rafiki270** [comment]
Well, that’s simple ... convert this and all subsequent projects (might not be necessary) and make them each an xcode project ... adding that I think will be the biggest challenge to get through the NIO guys and Tanner ... ;) unless we’ll get lucky this WWDC

**Comment by kdawgwilk** [comment]
Its a swift wrapper around a c library so that one might be tricky, you might have to do some header/modulemap magic to get that to work

**Comment by tanner0101** [comment]
vapor/sqlite now uses the `SQLite3` module available on iOS and macOS (still uses `CSQLite` on Linux). 

![screen shot 2018-06-14 at 9 37 39 pm](https://user-images.githubusercontent.com/1342803/41446015-2cb5dc62-701b-11e8-9740-e00825d51c58.png)

Tests appear to be passing when run on iPhone X simulator. Let me know if you guys manage to get it working in a real iOS project. Closing this issue for now. 👍

**Comment by twof** [comment]
Were you also seeing these warnings?
<img width="271" alt="screen shot 2018-06-15 at 10 03 33 am" src="https://user-images.githubusercontent.com/5561501/41480497-8957594c-7083-11e8-957d-e03c6ee33ede.png">

**Comment by tanner0101** [comment]
@twof I didn't see those in my build. Maybe the NIO guys would know more.

**Comment by broadwaylamb** [comment]
@kdawgwilk
> Would also need to support CocoaPods and Carthage unless we want to hold this off until WWDC and make a bet that SPM will finally be integrated into Xcode

looks like they did it 🎉🎉🎉

I've been able to use it in an iOS project, and it just works! (Well, there is [one slight edit](https://github.com/vapor/core/pull/206) I needed to make)

cc @tanner0101

**Comment by ismyhc** [comment]
Does anyone have the steps of getting this to work on iOS? Is there official support for it now? I looked in the swift package and the platform only specifies Mac_os ?

Any ideas @broadwaylamb @twof  ?

Thanks!

**Comment by alobaili** [comment]
> Does anyone have the steps of getting this to work on iOS? Is there official support for it now? I looked in the swift package and the platform only specifies Mac_os ?
> 
> Any ideas @broadwaylamb @twof ?
> 
> Thanks!

I managed to add `https://github.com/vapor/fluent-sqlite-driver.git` as a package dependency to a new iOS single-view application project and import `FluentSQLite`. The build was successful, but after that I'm not sure what to do.

I tried `SQLiteDatabase()` but I'm guessing we need some way to connect to the database in order for it to work.

I think a lead to the right direction on making FluentSQLite work on iOS will be much appreciated.

**Comment by twof** [comment]
@alobaili @ismyhc Check out this example: https://github.com/twof/iOSFluentExample/blob/master/iOSFluentApp/iOSFluentApp/ContentView.swift

The syntax might be slightly out of date because I created this demo while everything was still in beta, but the principles should still be correct.
