### ISSUE TITLE
Vapor does not honor foreign key constraints when using SQLite

### ISSUE THREAD

**Issue by patchthecode** [vapor/fluent-sqlite#9]
Say i had a `Region` model with one data in it
```
id | name
_____________
1  | Bellfare region
```
And say i had a `City` model which has region as a foreign key on it
```
id | name      | regionIdFk
1  | BigCity   | 2
```

Now in the City model example above, i put a region foreign id of 2 (which doesnt exist). 
Vapor should restrict this and let me know that region with the ID of `2` doesnt exist. But Vapor allows this to work.

### Steps to reproduce
Use SQLite Database. Create any foreign key constraint. And do something that should be illegal like above --> Put in a wrong foreign key.

I have ensured that I have done the correct foreign key constraint setup in migration:
```swift
final class City: Content {
    var id: Int?
    let regionId: Region.ID
    let name: String

extension City: Migration {
    static func prepare(on connection: SQLiteConnection) -> Future<Void> {
        return Database.create(self, on: connection) { builder in
            try addProperties(to: builder)
            try builder.addReference(from: \.regionId, to: \Region.id)
        }
    }
}
```

* Vapor Framework version: 3.0.0-rc.2.2.4
* Vapor Toolbox version: Vapor Toolbox: 3.1.4
* OS version: High Sierra

**Comment by tanner0101** [comment]
This will be fixed by adding a configuration line when the 3.0.0 tag is out:

```swift
databases.enableForeignKeys(on: .sqlite)
```

There will also be `disableForeignKeys(on:)` which will be useful for DBs like PostgreSQL and MySQL where foreign keys are enable by default 👍.

Thanks for reporting!

**Comment by mixio** [comment]
As of FluentSQLite-3.0.0, this as moved to [/FluentSQLite/SQLiteDatabase+SchemaSupporting.swift](https://github.com/vapor/fluent-sqlite/blob/master/Sources/FluentSQLite/SQLiteDatabase%2BSchemaSupporting.swift)

and enable/disableForeignKeys(on:) renamed to  enable/disableReferences(on:):

```swift
    /// See `SchemaSupporting`.
    public static func enableReferences(on conn: SQLiteConnection) -> Future<Void> {
        return conn.query("PRAGMA foreign_keys = ON;").transform(to: ())
    }
    
    /// See `SchemaSupporting`.
    public static func disableReferences(on conn: SQLiteConnection) -> Future<Void> {
        return conn.query("PRAGMA foreign_keys = OFF;").transform(to: ())
    }
```
